# Generated by Django 6.0.1 on 2026-01-28 15:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ວັນທີສ້າງ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ວັນທີອັບເດດ')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ອີເມວ')),
                ('user_type', models.CharField(choices=[('employer', 'ນາຍຈ້າງ'), ('admin', 'ແອດມິນ')], default='employer', max_length=20, verbose_name='ປະເພດຜູ້ໃຊ້')),
                ('is_active', models.BooleanField(default=True, verbose_name='ໃຊ້ງານຢູ່')),
                ('is_staff', models.BooleanField(default=False, verbose_name='ເປັນພະນັກງານ')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='ຢືນຢັນເບີໂທແລ້ວ')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP ເຂົ້າສູ່ລະບົບລ່າສຸດ')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ຜູ້ໃຊ້',
                'verbose_name_plural': 'ຜູ້ໃຊ້',
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ວັນທີສ້າງ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ວັນທີອັບເດດ')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='ອີເມວ')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('success', models.BooleanField(default=False, verbose_name='ສຳເລັດ')),
            ],
            options={
                'verbose_name': 'ການພະຍາຍາມເຂົ້າສູ່ລະບົບ',
                'verbose_name_plural': 'ການພະຍາຍາມເຂົ້າສູ່ລະບົບ',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'created_at'], name='accounts_lo_email_351ee0_idx'), models.Index(fields=['ip_address', 'created_at'], name='accounts_lo_ip_addr_71e387_idx')],
            },
        ),
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ວັນທີສ້າງ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ວັນທີອັບເດດ')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20, verbose_name='ເບີໂທ')),
                ('phone_normalized', models.CharField(db_index=True, max_length=20, verbose_name='ເບີໂທ (normalized)')),
                ('otp_code', models.CharField(max_length=6, verbose_name='ລະຫັດ OTP')),
                ('otp_expires_at', models.DateTimeField(verbose_name='OTP ໝົດອາຍຸ')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='ຈຳນວນຄັ້ງທີ່ລອງ')),
                ('status', models.CharField(choices=[('pending', 'ລໍຖ້າ'), ('verified', 'ຢືນຢັນແລ້ວ'), ('expired', 'ໝົດອາຍຸ')], default='pending', max_length=20, verbose_name='ສະຖານະ')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='ເວລາຢືນຢັນ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_verifications', to=settings.AUTH_USER_MODEL, verbose_name='ຜູ້ໃຊ້')),
            ],
            options={
                'verbose_name': 'ການຢືນຢັນເບີໂທ',
                'verbose_name_plural': 'ການຢືນຢັນເບີໂທ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type', 'is_active'], name='accounts_us_user_ty_029544_idx'),
        ),
    ]
