# Generated by Django 6.0.1 on 2026-01-28 15:08

import apps.companies.models
import apps.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ວັນທີສ້າງ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ວັນທີອັບເດດ')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='ຖືກລົບ')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='ວັນທີລົບ')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=150, verbose_name='ຊື່ບໍລິສັດ')),
                ('email', models.EmailField(max_length=254, verbose_name='ອີເມວຕິດຕໍ່')),
                ('phone_number', models.CharField(max_length=20, verbose_name='ເບີໂທ')),
                ('phone_normalized', models.CharField(db_index=True, max_length=20, verbose_name='ເບີໂທ (normalized)')),
                ('description', models.TextField(blank=True, verbose_name='ລາຍລະອຽດບໍລິສັດ')),
                ('address', models.TextField(blank=True, verbose_name='ທີ່ຢູ່')),
                ('website', models.URLField(blank=True, verbose_name='ເວັບໄຊ')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.companies.models.company_logo_path, validators=[apps.core.validators.validate_image_size, apps.core.validators.validate_image_extension], verbose_name='ໂລໂກ້')),
                ('status', models.CharField(choices=[('pending', 'ລໍຖ້າອະນຸມັດ'), ('active', 'ໃຊ້ງານໄດ້'), ('suspended', 'ຖືກລະງັບ')], db_index=True, default='pending', max_length=20, verbose_name='ສະຖານະ')),
            ],
            options={
                'verbose_name': 'ບໍລິສັດ',
                'verbose_name_plural': 'ບໍລິສັດ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ວັນທີສ້າງ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ວັນທີອັບເດດ')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='ຊື່')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='ຕຳແໜ່ງ')),
                ('phone_number', models.CharField(max_length=20, verbose_name='ເບີໂທ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ອີເມວ')),
                ('is_primary', models.BooleanField(default=False, verbose_name='ເປັນຜູ້ຕິດຕໍ່ຫຼັກ')),
            ],
            options={
                'verbose_name': 'ຜູ້ຕິດຕໍ່',
                'verbose_name_plural': 'ຜູ້ຕິດຕໍ່',
                'ordering': ['-is_primary', 'name'],
            },
        ),
    ]
