# Generated by Django 6.0.1 on 2026-01-28 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.province', verbose_name='ແຂວງ'),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL, verbose_name='ຜູ້ໃຊ້'),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='companies.company', verbose_name='ບໍລິສັດ'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['status', 'company_name'], name='companies_c_status_c301fa_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['province', 'status'], name='companies_c_provinc_5416f9_idx'),
        ),
    ]
