# Generated by Django 6.0.1 on 2026-01-28 15:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ວັນທີສ້າງ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ວັນທີອັບເດດ')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='ເລກໃບແຈ້ງໜີ້')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='ຈຳນວນເງິນ')),
                ('status', models.CharField(choices=[('pending', 'ລໍຖ້າຊຳລະ'), ('paid', 'ຊຳລະແລ້ວ'), ('expired', 'ໝົດອາຍຸ'), ('cancelled', 'ຍົກເລີກ')], db_index=True, default='pending', max_length=20, verbose_name='ສະຖານະ')),
                ('payment_reference', models.CharField(max_length=100, unique=True, verbose_name='ລະຫັດອ້າງອີງ')),
                ('qr_code_url', models.URLField(blank=True, verbose_name='QR Code URL')),
                ('qr_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='QR ໝົດອາຍຸ')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='ວັນທີຊຳລະ')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='Transaction ID')),
            ],
            options={
                'verbose_name': 'ໃບແຈ້ງໜີ້',
                'verbose_name_plural': 'ໃບແຈ້ງໜີ້',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ວັນທີສ້າງ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ວັນທີອັບເດດ')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='ຈຳນວນເງິນ')),
                ('status', models.CharField(choices=[('initiated', 'ເລີ່ມຕົ້ນ'), ('processing', 'ກຳລັງດຳເນີນການ'), ('completed', 'ສຳເລັດ'), ('failed', 'ລົ້ມເຫຼວ'), ('refunded', 'ຄືນເງິນ')], default='initiated', max_length=20, verbose_name='ສະຖານະ')),
                ('gateway', models.CharField(choices=[('bcel', 'BCEL One'), ('onepay', 'OnePay'), ('manual', 'Manual')], max_length=50, verbose_name='ຊ່ອງທາງຊຳລະ')),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=100, verbose_name='Gateway Transaction ID')),
                ('idempotency_key', models.CharField(max_length=100, unique=True, verbose_name='Idempotency Key')),
                ('gateway_response', models.JSONField(default=dict, verbose_name='Gateway Response')),
            ],
            options={
                'verbose_name': 'ການຊຳລະ',
                'verbose_name_plural': 'ການຊຳລະ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ວັນທີສ້າງ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ວັນທີອັບເດດ')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'ໃຊ້ງານໄດ້'), ('expired', 'ໝົດອາຍຸ'), ('suspended', 'ຖືກລະງັບ')], db_index=True, default='active', max_length=20, verbose_name='ສະຖານະ')),
                ('starts_at', models.DateTimeField(verbose_name='ວັນທີເລີ່ມ')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='ວັນທີໝົດອາຍຸ')),
            ],
            options={
                'verbose_name': 'ສະມາຊິກ',
                'verbose_name_plural': 'ສະມາຊິກ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ວັນທີສ້າງ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ວັນທີອັບເດດ')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='ຊື່ແພັກເກດ')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='ລາຄາ (LAK)')),
                ('duration_days', models.PositiveIntegerField(verbose_name='ໄລຍະເວລາ (ມື້)')),
                ('description', models.TextField(blank=True, verbose_name='ລາຍລະອຽດ')),
                ('features', models.JSONField(default=list, verbose_name='ຄຸນສົມບັດ')),
                ('is_active', models.BooleanField(default=True, verbose_name='ໃຊ້ງານຢູ່')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ລຳດັບ')),
            ],
            options={
                'verbose_name': 'ແພັກເກດ',
                'verbose_name_plural': 'ແພັກເກດ',
                'ordering': ['sort_order'],
            },
        ),
    ]
