# Generated by Django 6.0.1 on 2026-01-28 15:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ວັນທີສ້າງ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ວັນທີອັບເດດ')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ໃຊ້ງານຢູ່')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ລຳດັບ')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='ຊື່ໝວດໝູ່')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='ຊື່ພາສາອັງກິດ')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='ໄອຄອນ')),
            ],
            options={
                'verbose_name': 'ໝວດໝູ່',
                'verbose_name_plural': 'ໝວດໝູ່',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ວັນທີສ້າງ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ວັນທີອັບເດດ')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ໃຊ້ງານຢູ່')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ລຳດັບ')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='ຊື່ແຂວງ')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='ຊື່ພາສາອັງກິດ')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'ແຂວງ',
                'verbose_name_plural': 'ແຂວງ',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuickFilter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ວັນທີສ້າງ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ວັນທີອັບເດດ')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ໃຊ້ງານຢູ່')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ລຳດັບ')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='ຊື່ Filter')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='ໄອຄອນ')),
                ('filter_params', models.JSONField(default=dict, verbose_name='Parameters')),
            ],
            options={
                'verbose_name': 'Quick Filter',
                'verbose_name_plural': 'Quick Filters',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ວັນທີສ້າງ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ວັນທີອັບເດດ')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='ຖືກລົບ')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='ວັນທີລົບ')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='ຕຳແໜ່ງງານ')),
                ('description', models.TextField(verbose_name='ລາຍລະອຽດວຽກ')),
                ('requirements', models.TextField(blank=True, verbose_name='ຄຸນສົມບັດ')),
                ('benefits', models.TextField(blank=True, verbose_name='ສະຫວັດດີການ')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='ເງິນເດືອນຕ່ຳສຸດ')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='ເງິນເດືອນສູງສຸດ')),
                ('salary_negotiable', models.BooleanField(default=False, verbose_name='ຕາມຕົກລົງ')),
                ('job_type', models.CharField(choices=[('full_time', 'ເຕັມເວລາ'), ('part_time', 'ບາງເວລາ'), ('contract', 'ສັນຍາຈ້າງ'), ('internship', 'ຝຶກງານ'), ('freelance', 'ຟຣີແລນ')], default='full_time', max_length=20, verbose_name='ປະເພດວຽກ')),
                ('positions_count', models.PositiveSmallIntegerField(default=1, verbose_name='ຈຳນວນຕຳແໜ່ງ')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='ອີເມວຕິດຕໍ່')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='ເບີໂທຕິດຕໍ່')),
                ('contact_whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('contact_messenger', models.URLField(blank=True, verbose_name='Messenger')),
                ('status', models.CharField(choices=[('draft', 'ຮ່າງ'), ('published', 'ເຜີຍແຜ່ແລ້ວ'), ('closed', 'ປິດແລ້ວ'), ('expired', 'ໝົດອາຍຸ')], db_index=True, default='draft', max_length=20, verbose_name='ສະຖານະ')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='ວັນທີເຜີຍແຜ່')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='ວັນທີໝົດອາຍຸ')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='ຈຳນວນເບິ່ງ')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_posts', to='jobs.category', verbose_name='ໝວດໝູ່')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='companies.company', verbose_name='ບໍລິສັດ')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_posts', to='jobs.province', verbose_name='ແຂວງ')),
            ],
            options={
                'verbose_name': 'ໂພສວຽກ',
                'verbose_name_plural': 'ໂພສວຽກ',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ວັນທີສ້າງ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ວັນທີອັບເດດ')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ໃຊ້ງານຢູ່')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ລຳດັບ')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='ຊື່ Template')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='ໄອຄອນ')),
                ('template_type', models.CharField(choices=[('system', 'ລະບົບ'), ('custom', 'ກຳນົດເອງ')], default='system', max_length=20, verbose_name='ປະເພດ')),
                ('title_template', models.CharField(blank=True, max_length=200, verbose_name='ຕຳແໜ່ງ')),
                ('job_type', models.CharField(blank=True, max_length=20, verbose_name='ປະເພດວຽກ')),
                ('description_template', models.TextField(blank=True, verbose_name='ລາຍລະອຽດ')),
                ('requirements_template', models.TextField(blank=True, verbose_name='ຄຸນສົມບັດ')),
                ('benefits_template', models.TextField(blank=True, verbose_name='ສະຫວັດດີການ')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.category', verbose_name='ໝວດໝູ່')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_templates', to='companies.company', verbose_name='ບໍລິສັດ')),
            ],
            options={
                'verbose_name': 'Job Template',
                'verbose_name_plural': 'Job Templates',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ວັນທີສ້າງ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ວັນທີອັບເດດ')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20, verbose_name='ເບີໂທ')),
                ('phone_normalized', models.CharField(db_index=True, max_length=20, verbose_name='ເບີໂທ (normalized)')),
                ('keywords', models.CharField(blank=True, max_length=200, verbose_name='ຄຳຄົ້ນຫາ')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='ເງິນເດືອນຕ່ຳສຸດ')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS')], default='whatsapp', max_length=20, verbose_name='ຊ່ອງທາງແຈ້ງເຕືອນ')),
                ('frequency', models.CharField(choices=[('instant', 'ທັນທີ'), ('daily', 'ປະຈຳວັນ'), ('weekly', 'ປະຈຳອາທິດ')], default='instant', max_length=20, verbose_name='ຄວາມຖີ່')),
                ('is_active', models.BooleanField(default=True, verbose_name='ເປີດໃຊ້ງານ')),
                ('is_verified', models.BooleanField(default=False, verbose_name='ຢືນຢັນແລ້ວ')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='ສົ່ງລ່າສຸດ')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.category', verbose_name='ໝວດໝູ່')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.province', verbose_name='ແຂວງ')),
            ],
            options={
                'verbose_name': 'ການແຈ້ງເຕືອນວຽກ',
                'verbose_name_plural': 'ການແຈ້ງເຕືອນວຽກ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ວັນທີສ້າງ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ວັນທີອັບເດດ')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='Session Key')),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='jobs.jobpost', verbose_name='ໂພສວຽກ')),
            ],
            options={
                'verbose_name': 'ວຽກທີ່ບັນທຶກ',
                'verbose_name_plural': 'ວຽກທີ່ບັນທຶກ',
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ວັນທີສ້າງ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ວັນທີອັບເດດ')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100, verbose_name='ຊື່ເຕັມ')),
                ('phone_number', models.CharField(max_length=20, verbose_name='ເບີໂທ')),
                ('phone_normalized', models.CharField(db_index=True, max_length=20, verbose_name='ເບີໂທ (normalized)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ອີເມວ')),
                ('cover_message', models.TextField(blank=True, verbose_name='ຂໍ້ຄວາມ')),
                ('status', models.CharField(choices=[('new', 'ໃໝ່'), ('viewed', 'ເບິ່ງແລ້ວ'), ('contacted', 'ຕິດຕໍ່ແລ້ວ'), ('rejected', 'ປະຕິເສດ')], default='new', max_length=20, verbose_name='ສະຖານະ')),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobpost', verbose_name='ໂພສວຽກ')),
            ],
            options={
                'verbose_name': 'ໃບສະໝັກ',
                'verbose_name_plural': 'ໃບສະໝັກ',
                'ordering': ['-created_at'],
                'unique_together': {('job_post', 'phone_normalized')},
            },
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['status', 'published_at'], name='jobs_jobpos_status_d11b5a_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['status', 'expires_at'], name='jobs_jobpos_status_eed024_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['company', 'status'], name='jobs_jobpos_company_b5af56_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['category', 'status'], name='jobs_jobpos_categor_6a8b08_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['province', 'status'], name='jobs_jobpos_provinc_8dc7ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedjob',
            unique_together={('job_post', 'session_key')},
        ),
    ]
