# Generated by Django 6.0.1 on 2026-01-28 15:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ເວລາ')),
                ('actor_type', models.CharField(choices=[('system', 'ລະບົບ'), ('user', 'ຜູ້ໃຊ້'), ('admin', 'ແອດມິນ')], max_length=20, verbose_name='ປະເພດຜູ້ກະທຳ')),
                ('actor_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='ID ຜູ້ກະທຳ')),
                ('action', models.CharField(db_index=True, max_length=100, verbose_name='ການກະທຳ')),
                ('target_type', models.CharField(db_index=True, max_length=100, verbose_name='ປະເພດເປົ້າໝາຍ')),
                ('target_id', models.CharField(db_index=True, max_length=100, verbose_name='ID ເປົ້າໝາຍ')),
                ('details', models.JSONField(default=dict, verbose_name='ລາຍລະອຽດ')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
            ],
            options={
                'verbose_name': 'ບັນທຶກ',
                'verbose_name_plural': 'ບັນທຶກ',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor_type', 'actor_id'], name='audit_audit_actor_t_8bde50_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_audit_target__2d648a_idx'), models.Index(fields=['action', 'created_at'], name='audit_audit_action_766c6d_idx')],
            },
        ),
    ]
