# Generated by Django 6.0.1 on 2026-01-28 15:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportReason',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ວັນທີສ້າງ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ວັນທີອັບເດດ')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ໃຊ້ງານຢູ່')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ລຳດັບ')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='ເຫດຜົນ')),
            ],
            options={
                'verbose_name': 'ເຫດຜົນລາຍງານ',
                'verbose_name_plural': 'ເຫດຜົນລາຍງານ',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ວັນທີສ້າງ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ວັນທີອັບເດດ')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, verbose_name='ລາຍລະອຽດເພີ່ມເຕີມ')),
                ('reporter_phone', models.CharField(blank=True, max_length=20, verbose_name='ເບີໂທຜູ້ລາຍງານ')),
                ('reporter_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('status', models.CharField(choices=[('pending', 'ລໍຖ້າ'), ('reviewing', 'ກຳລັງກວດສອບ'), ('resolved', 'ແກ້ໄຂແລ້ວ'), ('dismissed', 'ຍົກເລີກ')], db_index=True, default='pending', max_length=20, verbose_name='ສະຖານະ')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='ວັນທີແກ້ໄຂ')),
                ('resolution_note', models.TextField(blank=True, verbose_name='ບັນທຶກການແກ້ໄຂ')),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='jobs.jobpost', verbose_name='ໂພສວຽກ')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL, verbose_name='ແກ້ໄຂໂດຍ')),
                ('reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.reportreason', verbose_name='ເຫດຜົນ')),
            ],
            options={
                'verbose_name': 'ການລາຍງານ',
                'verbose_name_plural': 'ການລາຍງານ',
                'ordering': ['-created_at'],
            },
        ),
    ]
